dist: bionic
language: cpp
sudo: required

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      cmake
      cmake-data
      qt5-default

compiler:
  - gcc
  - clang

script:
  - |
    env

    echo "$CXX"
    $CXX -v
